CC=gcc
CFLAGS=-I.

all: insertionsort selectionsort

insertionsort: insertionsort.c
	gcc -o insertionsort insertionsort.c

selectionsort: selectionsort.c
	gcc -o selectionsort selectionsort.c


clean:
	rm -rf insertionsort
	rm -rf selectionsort
